version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo 'date' 
      - mvn clean
  build:
    commands:
      - echo build on date & time
      - mvn package
  post_build:
    commands:
      - echo build is successfull on 'date'
artifacts:
  files:
    - target/ICICI_Web.war
    - aws s3 sync "s3://demo-static-s3site" --acl-read
