version: 0.2


phases:
  install:
    runtime-versions:
      java: coretto8
  pre_build:
    commands:
      - echo 'date' & 'time'
      - mvn clean
  build:
    commands:
      - echo build on date & time
      - mvn package
  post_build:
      - echo build is successfull on 'date'
artifacts:
  files:
    - target/ICICI_Web.war
    - aws s3 sync "s3://demo-static-s3site" --acl-read
